### ISSUE TITLE
Предварительная информация и материалы по второму семестру

### ISSUE THREAD

**Issue by Tka4uk-Andrei** [Tka4uk-Andrei/semesters_description#1]
Во втором семестре у нас будут следующие дисциплины:
- Научный дискурс
- Программирование биоинформатических приложений на суперкомпьютере
- Программирование сетей и инфокоммуникаций вычислительных комплексов
- ~Программирование систем анализа и обработки информации на основе современного инструментария и баз данных~
- Процессы управления качеством программного обеспечения
- Системы анализа больших данных
- Системы программирования
- ~Теория принятия решений в алгоритмах обработки больших данных~
- ~Управление информацией и хранением данных~
- Цифровая обработка многомерных сигналов

Если у вас есть какие-то материалы или информация о том, что будет просьба скидывать сюда в обсуждение или в личку ВК/tg

**Comment by Tka4uk-Andrei** [comment]
По сабд надо сделать один из следующих пунктов:

- Оформить pull request для проекта на github (макс. 20 человек)
- Сделать лабораторные связанные со стеком ELK (elastic search + kibana)
- Сделать оформление методички для лабораторных по стеку Grafana + Prometheus (не более 5 человек)

Для студентов получивших в прошлом "отлично" по результатам зачёта могут сделать только первые три лабораторные для стека ELK

TODO ссылки на методички

**Comment by Sonik-zirael** [comment]
По ЦОМС надо
* вести конспект, потому что его надо будет показать в конце семестра Сараджу (по опыту баки можно показать любую тетрадку с любым текстом)
* сделать две лабораторных из методички (работа номер 3 и 4) - главное сделать красивый отчёт и не забыть вставить подпись на титульник + подписать файл надо своей фамилией на кириллице(!)

**Comment by Sonik-zirael** [comment]
Научный дискурс
* ссылка на курс на dl https://dl.spbstu.ru/course/view.php?id=1901 
* выполнить два доклада с презентацией. Запись на доклад здесь: https://docs.google.com/spreadsheets/d/1N3oAku0JnyClVRJF9raLekdPmhJKv18RLNVn_HRQhVo/edit#gid=0 
* что должен включать каждый доклад можно посмотреть на дл

**Comment by Tka4uk-Andrei** [comment]
От Паши Гессена:

Итак, по Сарджу:
- Про таблички ему написал выше
- За семестр надо сделать 2 рассчетки
- 1ая (она под номером 3 в методичке) до середины марта
- 2ая (под номером 4) до конца сема
- По каждой работе нужен отчет (обязательно должна быть подпись на титульнике)
- Отчет присылать на яндекс почту
- Все отчеты называются следующим образом: ФИО_№группы_№задания (писать на кириллице!)
- Обязательно рукописный конспект (на экзе надо будет показать) 

По ЛП (Процессы управления качеством ПО):
- В течение семестра делается 1 курсовая
- По каждому этапу надо сделать часть отчета (или отдельный - надо уточнить)
- Сама курсовая: надо выбрать какой-то проект, который надо протестировать по методичке ЛП (проект может быть любой, в том числе и закрытый)

**Comment by Tka4uk-Andrei** [comment]
> Научный дискурс
> 
> * ссылка на курс на dl https://dl.spbstu.ru/course/view.php?id=1901
> * выполнить два доклада с презентацией. Запись на доклад здесь: https://docs.google.com/spreadsheets/d/1N3oAku0JnyClVRJF9raLekdPmhJKv18RLNVn_HRQhVo/edit#gid=0
> * что должен включать каждый доклад можно посмотреть на дл

@Sonik-zirael Спасибо! добавил

**Comment by Tka4uk-Andrei** [comment]
Распределение по системам программирования

https://docs.google.com/spreadsheets/d/1-re_gf1SFumRWIBWBuLjUr_nNh20KOhR7wCV_pjUnko/edit#gid=0

Надо поставить:
- ubuntu 12 (14)
- два доп. пакета

**Comment by Tka4uk-Andrei** [comment]
> По ЦОМС надо
> 
> * вести конспект, потому что его надо будет показать в конце семестра Сараджу (по опыту баки можно показать любую тетрадку с любым текстом)
> * сделать две лабораторных из методички (работа номер 3 и 4) - главное сделать красивый отчёт и не забыть вставить подпись на титульник + подписать файл надо своей фамилией на кириллице(!)

Учёл

**Comment by Tka4uk-Andrei** [comment]
Я вроде закончил с написанием, всю предложенную инфу в том или ином виде перенёс. Спасибо за помощь! 🥰🥰🥰
