### ISSUE TITLE
Описание 3 го семестра

### ISSUE THREAD

**Issue by Tka4uk-Andrei** [Tka4uk-Andrei/semesters_description#3]
Тут можно написать, что и по каким предметам нас ждёт в третьем семе.

P.S.
Если не лень можете PR создать.

**Comment by Tka4uk-Andrei** [comment]
https://levutkin.github.io/teaching/machine-learning
Материалы Уткина

**Comment by Sonik-zirael** [comment]
Мне не лень создать PR, но у меня нет прав на пуш в этот репозиторий :)

**Comment by Tka4uk-Andrei** [comment]
> Мне не лень создать PR, но у меня нет прав на пуш в этот репозиторий :)

Добавил)

**Comment by Tka4uk-Andrei** [comment]
Предварительный сбор и оформление информации окончен
